### ISSUE TITLE
Action error: `uninitialized constant Faraday::Request::Retry `

### ISSUE THREAD

**Issue by pat-s** [naijabcom/update-formula-homebrew-action#2]
Could it be that the action needs an update WRT to dependencies?

https://github.com/pat-s/rcli/runs/6737477026?check_suite_focus=true

```
/usr/bin/docker run --name d3d7b198e24354b5db410b16e8be73177_95d04d --label 08450d --workdir /github/workspace --rm -e COMMIT_TOKEN -e INPUT_REPO -e INPUT_TAP -e INPUT_FORMULA -e INPUT_DOWNLOAD-URL -e INPUT_SHA256 -e INPUT_COMMIT-MESSAGE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/rcli/rcli":"/github/workspace" 08450d:3d7b198e24354b5db410b16e8be73177  "--repository" "pat-s/rcli" "--tap" "pat-s/homebrew-rcli" "--formula" "Formula/rcli.rb" "--download-url" "https://github.com/pat-s/rcli/releases/download/0.9.1/rcli" "--sha256" "b790f9a8ff0684fbaf5a92299664ae16a802c6515929e140df3dba9d18a2a082" "--commit-message" "update rcli formula"
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
F, [2022-06-04T09:51:38.747018 #1] FATAL -- : uninitialized constant Faraday::Request::Retry (NameError)
/entrypoint.rb:61:in `block in <main>'
/usr/local/bundle/gems/faraday-2.3.0/lib/faraday/rack_builder.rb:75:in `build'
/usr/local/bundle/gems/faraday-2.3.0/lib/faraday/rack_builder.rb:64:in `initialize'
/entrypoint.rb:60:in `new'
/entrypoint.rb:60:in `<main>'
```

**Comment by naijab** [comment]
Thanks, for notify that error, I will fix after weekend 🥹

**Comment by pat-s** [comment]
Just tried the WF again, it still errors :( Any chance you can find some time to bump the WF in the next days? Otherwise I need to look for other solutions to create new releases which I'd like to avoid.

**Comment by naijab** [comment]
@pat-s  Sorry bro, I'm fixing now

**Comment by naijab** [comment]
@pat-s please try change use from `naijabx/update-formula-homebrew-action@v1` to `naijabx/update-formula-homebrew-action@v1.1`

**Comment by pat-s** [comment]
Awesome, thanks! Works fine again!
